### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Coooopzy** [Waradu/Mond#2]
Could you please make this in English?

**Comment by Waradu** [comment]
Just navigate to the mond.widget folder and open index.coffee.
After that under settings change lang to 'en'

![Bildschirmfoto 2023-01-18 um 11 53 55](https://user-images.githubusercontent.com/89935135/213153402-13b69cc1-f6dd-4f2d-98ef-53439d301962.png)

![Bildschirmfoto 2023-01-18 um 11 54 05](https://user-images.githubusercontent.com/89935135/213153437-1a4be16d-e451-42b3-bc0b-ade9a14332b0.png)

**Comment by Coooopzy** [comment]
I am using a mac and when I click on the file it won't open, is there
another way to access it?

**Comment by Waradu** [comment]
download the newest version, the default is set to english.
Or use another editor like VSCode or your browser (rightclick > open with)
